name: Backend CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'my_flow_api/**'
      - '.github/workflows/backend-ci.yml'
  push:
    branches: [main]
    paths:
      - 'my_flow_api/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('my_flow_api/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          cd my_flow_api
          uv sync

      - name: Run linting (ruff)
        run: |
          cd my_flow_api
          uv run ruff check .

      - name: Run type checking (mypy)
        run: |
          cd my_flow_api
          uv run mypy src/

      - name: Run tests (pytest)
        run: |
          cd my_flow_api
          PYTHONPATH=. uv run pytest --cov=src --cov-report=term --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./my_flow_api/coverage.xml
          flags: backend
          fail_ci_if_error: false
