name: Frontend CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'my_flow_client/**'
      - '.github/workflows/frontend-ci.yml'
  push:
    branches: [main]
    paths:
      - 'my_flow_client/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_LOGTO_ENDPOINT: ${{ secrets.NEXT_PUBLIC_LOGTO_ENDPOINT }}
      NEXT_PUBLIC_LOGTO_APP_ID: ${{ secrets.NEXT_PUBLIC_LOGTO_APP_ID }}
      LOGTO_APP_SECRET: ${{ secrets.LOGTO_APP_SECRET }}
      LOGTO_COOKIE_SECRET: ${{ secrets.LOGTO_COOKIE_SECRET }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:8000' }}
      NEXT_PUBLIC_LOGTO_RESOURCE: ${{ secrets.NEXT_PUBLIC_LOGTO_RESOURCE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd my_flow_client
          bun install

      - name: Run linting (ESLint)
        run: |
          cd my_flow_client
          bun run lint

      - name: Run type checking (TypeScript)
        run: |
          cd my_flow_client
          bun run typecheck

      - name: Run tests (Vitest)
        run: |
          cd my_flow_client
          bun run test -- --coverage

      - name: Verify Logto secrets are present
        run: |
          node -e "const required=['LOGTO_COOKIE_SECRET','LOGTO_APP_SECRET','NEXT_PUBLIC_LOGTO_ENDPOINT','NEXT_PUBLIC_LOGTO_APP_ID']; const optional=['NEXT_PUBLIC_LOGTO_RESOURCE','NEXT_PUBLIC_BASE_URL','NEXT_PUBLIC_API_URL']; const missing=required.filter((key)=>!process.env[key]); if(missing.length){throw new Error('Missing required secrets: '+missing.join(', '));} const skipped=optional.filter((key)=>!process.env[key]); if(skipped.length){console.log('⚠️ Optional secrets not set: '+skipped.join(', '));}"

      - name: Build verification
        run: |
          cd my_flow_client
          bun run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./my_flow_client/coverage/coverage-final.json
          flags: frontend
          fail_ci_if_error: false
